// <auto-generated />
using System;
using AlgoRunner.Api.Dal.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AlgoRunner.Api.Migrations
{
    [DbContext(typeof(AlgoRunnerDbContext))]
    partial class AlgoRunnerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminInfoId");

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.Property<string>("ServerPath");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("AdminInfoId");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.AdminInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("AdminInfos");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.AlgResultType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("AlgResultTypes");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.AlgoDotesResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlgoName");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.ToTable("AlgoDotesResults");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.AlgoExecutionParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExecutionInfoId");

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("ExecutionInfoId");

                    b.ToTable("AlgoExecutionParams");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.AlgoParam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AlgorithmId");

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.Property<string>("Value")
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.HasIndex("AlgorithmId");

                    b.ToTable("AlgoParams");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.AlgoTableResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlgoName");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.ToTable("AlgoTableResults");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.AlgoTextResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlgoName");

                    b.Property<int>("TypeId");

                    b.HasKey("Id");

                    b.ToTable("AlgoTextResults");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.Algorithm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Desc");

                    b.Property<string>("FileServerPath")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.Property<int?>("ProjectAlgoListProjectId");

                    b.Property<int?>("ProjectId");

                    b.Property<int>("ResultTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ProjectAlgoListProjectId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ResultTypeId");

                    b.ToTable("Algorithms");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.ExecutionInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlgoId");

                    b.Property<string>("AlgoName");

                    b.Property<DateTime?>("EndDate");

                    b.Property<string>("ExecutedBy")
                        .HasMaxLength(250);

                    b.Property<string>("FileExePath")
                        .HasMaxLength(1000);

                    b.Property<int>("ProjectExecutionId");

                    b.Property<int>("ProjectId");

                    b.Property<string>("ProjectName");

                    b.Property<DateTime?>("StartDate");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ExecutionInfos");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Context");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Title");

                    b.Property<string>("UserName");

                    b.Property<bool>("isReaded");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ResultCategoryLabel");

                    b.Property<float>("X");

                    b.Property<float>("Y");

                    b.HasKey("Id");

                    b.HasIndex("ResultCategoryLabel");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActivityId");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(250);

                    b.Property<string>("Desc");

                    b.Property<bool>("IsFavorite");

                    b.Property<DateTime>("LastExecutionDate");

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.ProjectAlgo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlgoId");

                    b.Property<int>("ProjectId");

                    b.HasKey("Id");

                    b.ToTable("ProjectAlgos");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.ProjectAlgoList", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ProjectId");

                    b.ToTable("ProjectAlgoLists");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.ProjectExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("ExecutedBy")
                        .HasMaxLength(250);

                    b.Property<string>("ResultPath");

                    b.Property<DateTime>("StartDate");

                    b.HasKey("Id");

                    b.ToTable("ProjectExecutions");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.ResultCategory", b =>
                {
                    b.Property<string>("Label")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250);

                    b.Property<int?>("AlgoDotesResultId");

                    b.HasKey("Label");

                    b.HasIndex("AlgoDotesResultId");

                    b.ToTable("ResultCategories");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdminInfoId");

                    b.Property<bool>("IsAdmin");

                    b.Property<string>("Name")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("AdminInfoId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.Activity", b =>
                {
                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.AdminInfo")
                        .WithMany("Activities")
                        .HasForeignKey("AdminInfoId");

                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.User")
                        .WithMany("Activities")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.AlgoExecutionParam", b =>
                {
                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.ExecutionInfo")
                        .WithMany("ExeParams")
                        .HasForeignKey("ExecutionInfoId");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.AlgoParam", b =>
                {
                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.Algorithm")
                        .WithMany("AlgoParams")
                        .HasForeignKey("AlgorithmId");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.Algorithm", b =>
                {
                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.ProjectAlgoList")
                        .WithMany("Algos")
                        .HasForeignKey("ProjectAlgoListProjectId");

                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.Project")
                        .WithMany("AlgorithmsList")
                        .HasForeignKey("ProjectId");

                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.AlgResultType", "ResultType")
                        .WithMany()
                        .HasForeignKey("ResultTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.ExecutionInfo", b =>
                {
                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.Project")
                        .WithMany("ExecutionsList")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.Point", b =>
                {
                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.ResultCategory")
                        .WithMany("Data")
                        .HasForeignKey("ResultCategoryLabel");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.Project", b =>
                {
                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.ResultCategory", b =>
                {
                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.AlgoDotesResult")
                        .WithMany("Categories")
                        .HasForeignKey("AlgoDotesResultId");
                });

            modelBuilder.Entity("AlgoRunner.Api.Dal.EF.Entities.User", b =>
                {
                    b.HasOne("AlgoRunner.Api.Dal.EF.Entities.AdminInfo")
                        .WithMany("Members")
                        .HasForeignKey("AdminInfoId");
                });
#pragma warning restore 612, 618
        }
    }
}
